=== BrainStop/ICD-TrabalhoPratico-1/restaurante (2)/restaurante.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2016 rel. 2 (x64) (http://www.altova.com) by Diogo Remedios (Instituto Superior de Engenharia de Lisboa) -->
<!-- Eng. P, Filipe -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="AT_latLonListType">
		<xs:annotation>
			<xs:documentation>valida pares latitude e longitude
               (i.e. 38.732533,-9.147221)
 </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[\-]?\d{1,2}\.\d+,[\-]?\d{1,3}\.\d+( [\-]?\d{1,2}\.\d+,[\-]?\d{1,3}\.\d+)*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AT_emailAddress">
		<xs:annotation>
			<xs:documentation>valida endereço de email</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AT_mime">
		<xs:annotation>
			<xs:documentation>tipo de imagens</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="image/jpg"/>
			<xs:enumeration value="image/png"/>
			<xs:enumeration value="image/gif"/>
			<xs:enumeration value="image/bmp"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AT_Dsg">
		<xs:annotation>
			<xs:documentation>padrão aplicado a designações (minusculas)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z|áàãâéèíìóòõôúùç ']{1,60}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="AT_Ingrediente">
		<xs:annotation>
			<xs:documentation>tipo associado á definição do ingrediente</xs:documentation>
		</xs:annotation>
		<xs:group ref="lingua"/>
		<xs:attribute name="idingrediente" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:group name="lingua">
		<xs:annotation>
			<xs:documentation>groupo de elementos que implementa multilingua (não implementa restriçoes de unicidade!)</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="pt-pt" type="AT_Dsg"/>
			<xs:element name="en-uk" type="AT_Dsg" minOccurs="0"/>
			<xs:element name="fr-fr" type="AT_Dsg" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:element name="url" type="xs:anyURI">
		<xs:annotation>
			<xs:documentation>representa um URL (referencia externa)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="serve">
		<xs:annotation>
			<xs:documentation>atribui um preço a um item que figura numa ementa</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="preço" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:totalDigits value="4"/>
						<xs:fractionDigits value="1"/>
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="iditem" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="imagem">
		<xs:annotation>
			<xs:documentation>representa uma imagem</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="mime" type="AT_mime" use="required">
						<xs:annotation>
							<xs:documentation>tipo original do ficheiro</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="path" type="xs:anyURI">
						<xs:annotation>
							<xs:documentation>nome/caminho original do ficheirro</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="encoding" type="xs:string" default="xs:base64Binary">
						<xs:annotation>
							<xs:documentation>exemplo: <img src="data:image/jpg;base64,........CONTEUDO EM BASE64......"/>
							</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="itens">
		<xs:annotation>
			<xs:documentation>representa um conjunto de itens</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="aken-uk">
			<xs:selector xpath="item/en-uk"/>
			<xs:field xpath="."/>
		</xs:unique>
		<xs:unique name="akfr-fr">
			<xs:selector xpath="item/fr-fr"/>
			<xs:field xpath="."/>
		</xs:unique>
	</xs:element>
	<xs:element name="item">
		<xs:annotation>
			<xs:documentation>representa um item</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="lingua"/>
				<xs:element name="ingrediente" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="idingrediente" type="xs:IDREF" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:choice minOccurs="1">
					<xs:element ref="imagem" minOccurs="0"/>
					<xs:element ref="url" minOccurs="0"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="tipo" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="entrada"/>
						<xs:enumeration value="carne"/>
						<xs:enumeration value="peixe"/>
						<xs:enumeration value="doce"/>
						<xs:enumeration value="fruta"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="iditem" type="xs:ID" use="required"/>
		</xs:complexType>
		<xs:unique name="akitpt">
			<xs:selector xpath="pt-pt"/>
			<xs:field xpath="."/>
		</xs:unique>
		<xs:unique name="akituk">
			<xs:selector xpath="en-uk"/>
			<xs:field xpath="."/>
		</xs:unique>
		<xs:unique name="akitfr">
			<xs:selector xpath="fr-fr"/>
			<xs:field xpath="."/>
		</xs:unique>
	</xs:element>
	<xs:element name="ingredientes">
		<xs:annotation>
			<xs:documentation>representa um conjunto de ingredientes</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ingrediente" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ingrediente" type="AT_Ingrediente">
		<xs:annotation>
			<xs:documentation>representa um ingrediente</xs:documentation>
		</xs:annotation>
		<xs:unique name="akigpt">
			<xs:selector xpath="pt-pt"/>
			<xs:field xpath="."/>
		</xs:unique>
		<xs:unique name="akiguk">
			<xs:selector xpath="en-uk"/>
			<xs:field xpath="."/>
		</xs:unique>
		<xs:unique name="akigfr">
			<xs:selector xpath="fr-fr"/>
			<xs:field xpath="."/>
		</xs:unique>
	</xs:element>
	<xs:element name="ementas">
		<xs:annotation>
			<xs:documentation>representa um conjunto de ementas</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ementa" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ementa">
		<xs:annotation>
			<xs:documentation>representa uma ementa</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="serve" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="tipo" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="almoço"/>
						<xs:enumeration value="jantar"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="modo" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="diaútil"/>
						<xs:enumeration value="fds-feriado"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
		<xs:key name="pkserve">
			<xs:selector xpath="serve"/>
			<xs:field xpath="@iditem"/>
		</xs:key>
	</xs:element>
	<xs:element name="restaurante">
		<xs:annotation>
			<xs:documentation>representa um restaurante</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="imagem">
					<xs:annotation>
						<xs:documentation>logotipo</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="ingredientes">
					<xs:annotation>
						<xs:documentation>registo de ingredientes</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="itens">
					<xs:annotation>
						<xs:documentation>registo de itens</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="ementas">
					<xs:annotation>
						<xs:documentation>registo de ementas</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="email" type="AT_emailAddress" use="required"/>
			<xs:attribute name="designação" type="AT_Dsg" use="required"/>
			<xs:attribute name="coordenadas" type="AT_latLonListType" default="38.755787,-9.116290"/>
		</xs:complexType>
		<xs:key name="pkitem">
			<xs:selector xpath="itens/item"/>
			<xs:field xpath="@iditem"/>
		</xs:key>
		<xs:keyref name="fkitem" refer="pkitem">
			<xs:selector xpath="ementas/ementa/serve"/>
			<xs:field xpath="@iditem"/>
		</xs:keyref>
		<xs:key name="pkingrediente">
			<xs:selector xpath="ingredientes/ingrediente"/>
			<xs:field xpath="@idingrediente"/>
		</xs:key>
		<xs:keyref name="fkingrediente" refer="pkingrediente">
			<xs:selector xpath="itens/item/ingrediente"/>
			<xs:field xpath="@idingrediente"/>
		</xs:keyref>
	</xs:element>
</xs:schema>

=== BrainStop/ICD-TrabalhoPratico-1/Eclipse/trabalho pratico 1/src/tp_01/database/restaurante.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!-- Eng. P. Filipe !-->
<?xml-stylesheet type="text/xsl" href="ementa-to-html.xsl"?>
<restaurante coordenadas="38.755787,-9.116290" designação="o garfo do isel" email="garfo@isel.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="restaurante.xsd">
	<imagem mime="image/jpg" path="fork-restaurant-isel.jpg" encoding="xs:base64Binary">/9j/4AAQSkZJRgABAQEAYABgAAD/4QAWRXhpZgAATU0AKgAAAAgAAAAAAAD/7AARRHVja3kAAQAEAAAARgAA/+EDZmh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4NCjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNS1jMDIxIDc5LjE1NTc3MiwgMjAxNC8wMS8xMy0xOTo0NDowMCAgICAgICAgIj4NCgk8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPg0KCQk8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDowODcyNjI0QjFBMUYxMUU0QTZFNDg0MDEwQUY5REJEQiIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDowODcyNjI0QTFBMUYxMUU0QTZFNDg0MDEwQUY5REJEQiIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxNCAoTWFjaW50b3NoKSI+DQoJCQk8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0iYWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOmUwMDYxZGExLTYyN2YtMTE3Ny05ZGRmLWQ4ZWJjN2U0NGEzMCIgc3RSZWY6ZG9jdW1lbnRJRD0iYWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOmUwMDYxZGExLTYyN2YtMTE3Ny05ZGRmLWQ4ZWJjN2U0NGEzMCIvPg0KCQk8L3JkZjpEZXNjcmlwdGlvbj4NCgk8L3JkZjpSREY+DQo8L3g6eG1wbWV0YT4NCjw/eHBhY2tldCBlbmQ9J3cnPz7/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCACGAKsDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9+H+//n/P+TX89/hT/g5W/aW17xTptjJ/wr/beXUUDY0Rg2GdV4Pm+/Bx1r+hP+P8K/jy+Ddp9t+LnhOHbu83V7RNvrumQUAfth/wW8/4LE/GH/gn/wDtc6L4L8At4VOj33hW21eT+0dNa4l8+S6uomw28fLthTj1q747/wCCvfxe8P8A/BErwX8frdvC/wDwn2veKJNIut2mk2XkLcXsYxFvyGxBHzu65r5K/wCDpo/8bFfDP/Yg2P8A6X6jWl8WP+VXL4X/APY/Tf8ApZqdAH1t/wAEMP8AgrJ8W/8Agob8XfHmh+Pm8MfZfD+hxX9j/Z+nNbN5zTbDvPmNlcEelfFfgn/g5W/aS1zxjpNjcN4D+z3l5DDJt0Rg2xnCn5vN64J59a77/g0+OP2lfip/2LMH/pUv/wCqvzI8FWv2H4xaRBt2eTrEKbfTE4FAH9ha8CiiigAoor5X/ag/4KS2HgceINI+Ha6Tr+oeGY5X1/xFfPKfD/hgRQ+fKsjQK8t5cpCQ5trZWZFdXlaGPc4xrV4Uo802duBy+vjKns6Ebvr2Xr+i3b0Sb0PpXxh420b4eeHrjV/EGraZoek2a7p73ULpLW3hHq0jkKo+pr5r+IH/AAVs+Huj+HJtU8IaT4m8e6XEG/4ntvHBo3hkMpAYHWNSltrEkMQuEldizABTzjz74d/8E/vG37Teo6f4w+Lniq+vGmiiurN9Qjtb2/gLBSTbWA83StLX5FIKrqFziQst5C4xVf4bfBPwtF+z3D41utHttY8cR/G1tGHibVs6jrZs7P4htY20BvZ98+xLa3ijxvwQpJyWYnhqYjES1iuVWb130/D5fifR4XLMspfxZOrLmjFpaRvK/XRtaPVNPo4lSb/gqj8VfiRfNY+CfA/w/XUpIGuYLWK48Q+KpWiWTy/OMmm6X9i2FuARd7SQw38EjLi/4KGftHXXhS316HRfh/NoV3qqaDDqqeDtV+wtqD6iNLS33Nfibeb0iD/UkBmBJ2guPp9D/wAbJJP+yaL/AOnRq8E8Ef8AKNLwv/2XTTv/AFacVYyjVbfNUeiltptb/M9GjVwXuKlhopSlSWvvWVRSbs2r6cqte/W5Uf8A4KSfHT4XpcN4z+HXgq5jtnYPI9h4s8NQEds3dxpFxYIe/wA12FIH3hzjuvhf/wAFifBPiXRJtQ8VeFPFnhfSrEEX/iHSzbeL/DVgwOCJtR0eW6S2xxn7UsBAOSBg4+vK87+LX7J3w6+N+u2+seJPCem3HiKzQR2mv2m/T9bsVHIEGoW7R3UPPP7uVa6vq+JjrCpfya/N7niLMsqraYjDON95Qlr8o6RXzT+Z0Pws+MHhP44+EYdf8GeJdB8V6HcHbHf6TfRXluxHVd8ZI3DuDyO4ro6+Fvi7/wAEt/E3w38aXPjr4R+KtYj8Tu7zXF3BeQ6P4julHziN7pYjZasu5QPK1e1llkL/ADX8IGa0P2ff+Cn2peAdSbwx8e7eHRzYzW9g3jSPTJtLtLa4lfy4YNasZSz6TPKRlJw8un3HzmC5ZVAqo4xxfJiFyvv0/wCB+ncmtkMK1N1ssqe0S3jtNfL7Xa6s272jZNn2zRQG3DI5B6Giu4+bCiiigBP4/wAK/kG/ZosxqH7RXw/t2+7N4k06P87mOv6+f4/wr+Rb9jqD7V+1v8K4f+e3jDSE/O8iFAH3L/wdN/8AKRPwz/2INj/6X6jWj8WP+VXL4X/9j9N/6WanWb/wdNnH/BRTwx/2INj/AOl+o1pfFj/lVy+F/wD2P03/AKWanQB0P/Bp4P8AjJb4qf8AYswf+lS1+a1pbCz/AGioYR0i8RBPyucV+lX/AAae/wDJy3xU/wCxZg/9Kl/wr85fEEH2T9rO9h/55eLZE/K8YUAf12UUDpXzD/wUg/abuvh74atfh34XvdTs/F3i6zku7y70uNZtQ0bR0ljhnntoiCZL2eSaKztIwp33V1CCUGWGVasqUHNnZgMFPF140KfXr2XV/L8dlqea/tvftxXHxB1zUPAvg281yz8K6dcS2XiDWtEjL6hrEsQX7RZWLhWWGCHzIvtV6+FiMsMSkyTIG920Lw98Kf8AgnT8LtLutYvdL8MaY80OiLqk8LR29sZXZ1j3fN9ngL75HkkbBdnmmkeR5JW8pk/ZOsf2df2FvF1/daPZ6Z4r1fSLeG5toJjcxaDaLOrxaXBM3zSRxNJI0kzHfc3EtxcP80uF7/8A4KRa3q/hr4e/D/UvD+lrrmuaf480y5sdNaf7P/aMqJOwgD4IVnxtUnjcwyQMkedHni5VanxWTWl7Xb6fL+tW/qKn1erGjg8NdU3KaeqXNyxi7tu6Wrerura6JJLYuvhvrH7KPnav8NdNm13wFM5uNS8D2zDzNOB5a50XJCp1JexJEUnDwmGQSJdeRfCrVIdc/Ybsb63Mht7748XV1F5kTQyBJPiZNIu+NwHjbawyjhWU5DAEED47+DH/AAXci+BJvrfw58NbqHwrdkNaeFpdb/0HQW5J+wyGEyQQNkD7IVMUe1fK8ld0beex/wDBVLStJlmv9G8A6lo2rah4wPi3WFh1xW0/X2GvnWIkuYDCP38S7LdLtCspSJA4eNUiTyZZ7g/sy0s1az0vbbT8NPls/tKHh7nrVqtG7U4SUuaF5JKV1Jc26vur3b1bXvL9ZE/5SSyf9k0X/wBOjV4J4I/5RpeF/wDsumnf+rUir5ktv+C8V9qf7RFp42034U3Goa/f6KPCkGjw6rv+1u92ktv5RERZpZJHaPZt5JjwSSRVP9qf43/F74W/8E+PB9rpmh6ZaeB/EXifxNHqt1Gy6hNpWrQ+J9TuBG+Ywm1TEjwTrwHgmLKG8hq0lm2HlCdWneSSlsn1cbb/AI9jmo8GZlRxGHwuKUacpTpWvKP2I1ObZt+nd6I/Wj43/GTRf2fvhZq/jDxC10uj6JGkly1vF5kgDSLGDjIAG5xlmIVRliQASPAv2Qv+Ctfw9/bV/aCuvAHhHSvElvcW+iXOti91CKKKJ0gntoWjAV2O5jdKy4JyqPnbgA/nF4a/4LN+IbD9hWz+D2ueGrXxVcJps/h291G/uHzf6WymOJCykOk8cREZk+dn2B9yuS1fI3wa+NXiD4N+MD4i8F69daTrFnHJZPeadctG8QcKXiZkYEZwp2k9lOOBXLiuKEqsJUdYWvJW19LnsZR4Qzlg8RDHrlrczVOXN7rXRtLXW19ejWl0z92f2vv+Cs3w9/Yq+NVn4M8V6T4ovpbyxjvDeaTFBNHalmYFJVkljYYXY2V3EhxxXTeLPhf8Pf8Ago/8CtC8b6LJcWFxrOlS/wBg+Iv7OCXkVrOCktvPBOuy6spsYltLhXgmXa23IjkX8B/jP+0B4j+O/ii11Hxjr0mrawsJtori4cG4mC8/Mx+aRgGUZYkhRGvChQPsDwb/AMFtfEXh79iRvhOvhXTNJ1DRNBtvD2iarpksixtaQxLbrHJC5YowiRd0iyHf8yqkRYOk4fiSFSdRYn4Le6ra/evw/M1zLwqxOFw+FnlOtdO1SSkuVdLqL1a7rtdNNH1R+zd8f/En/BNDxq3wz+J6yW3w0tPL+y3ElzJcxeDYJJlghuLWeQmSfQHleKL96zXGlyyRw3BeCS2upP0OByK/KP8A4JoRfFz/AIKN/AfxDpPjz7DrmieA0dfBnjbxBE9xfnVHj8ubTpwQRqWmSW7NFeLKQzpOYt8jnda/Qv8AwSz+N2oeAtWvfgT4oFxZS6JDc3fhK2vLuS6u9MtbecQ3ugzTuP30unSSQeTKMC40+7sJ1VVYge1luLvGGjUJL3b7ry/y/Dey+D4qyW1Ws7xdei7VFF3Ur/aXW6+0t93LVOU/teiiivaPz8T+P8K/km/YPtft37cHwZhxu87x1oabfXdqEAr+tn+P8K/kA/Z5+I8fwf8Aj74F8Wyh2j8K6/p+sME5Yi3uY5T+ifhwaAP3Z/4Lhf8ABGPxb/wUR+IHhHxz8PtW8P2XiLSdPGhalbaxPJBDPaCZ5Y5EdI3+dGll3KQAwYYIIwe++In/AAR3t/EX/BIbS/2bdP16Bdc0GBNQstZnjYW8urefJcyO6jLCGR5po8kMVRwcEqAftvw7rln4m0Cx1LTriG80/UIEubW4ibdHPE6hkdT3UqQQfQ1eoA/Pj/gh1/wSO8R/8E4NK8Za7471TR77xd4u8mzjg0uV5rewtIizcyMqFnkd8kBcKI1w2SQPws+Kdr9g/bi8RQbdvk+OLmPbgDbi/cY447duK/rC8a+L9N+H/hLVte1i8jsNH0Wzlvr25kIWO3hjQu7k9tqqTX8jyeMX+If7SC+IJFKya74k/tFgTnBmujIf/QqAP68NY1e18P6RdX95MlvZ2ML3E8rfdijRSzMfYAE1+anwO+Mdj8Uv2wfBfxQ8XWu3RfiV4stVtzcTZgsriXTL1/DNmUyyM0VkovGwFLXHiOxc82qFfqr/AIKleKZNP/ZHvvC9tqTaNffFDV9N8CwX4UlbFNRuo4LiZsdFjtjcOSeAF5wMmvlT4++FrfQf2A/hZrUOja7Y33xF8QXviq0i0gNJqujXN9ZXMuimG3VgbmWwA0uNbZTlhZKMMVw3j5hVftEltGz+d0v68mz7nhnBw+rNz3rNwXRpcrd/NX6d4o+3/wBuH/k1Pxn/ANeif+jo6xf23P8AmkX/AGUvRv8A2tXNePPjpaftLf8ABMyXxzZtYf8AFQaJDNcx2V2l3b212syR3MCTRsySiKdJY96MytsyrEEE9L+23/zSL/spejf+1q6ZyUm5R2aj+bPKw9GdKNOlUVpRnVTXmoQTPyl/4Lg/sXr+zP8AtSN4u0W18rwj8Tnm1KMIp2WWphg15D3wJGdZ1yRkyzKoCxV8W1/Rh/wUM/ZMt/20P2UvEvgvy7f+2/L/ALQ0C4mwotdShBaE7sHar5aJyBny5pAOtfzw6X4I17X/ABta+FdP0e8m8V32pJottpMq+TcG/eYQLbOG/wBWwlOxt2AmGLYCnHwnEOWuhiuamtJ6r16r+u5/RnhjxXHMMn9nipe/h1aTb+yl7sn8k035Xe59d/8ABHr/AIJ6WH7bniLxtreqeJdS8O2/gmK3i0u60S/WDVbDV5GE0F2uCWRYVi3KWUB2kG1sxNhP2+/hf+0R8K9T8K/A/XLC71/SdW1S8OgXWgQEW3jO6vdQnvn+XhYXWSYs8EhAj8rzGkeJElH6efB//gm1oPwP/Zv8EeGPC+rT+HfH3gexdbPxnYQD7TNeTuJrwzxMdtxZ3E+We0lJQKI9hjkhhlj3tN8eab8aZD8I/jN4fs9F8bXERurWGCeWOw8RLAQ41HRrsFZUmhYJIY1ZLuzkCtkp5NzL70MhhHDKhJuMnu09JX3i/wAl8t9Ufm9bxGq1s1nmNOCq0o35YSXvU7JpVI7NreUldWu0+W0ZnzX+w1/wQO8D/CvRLHXvjNFZfELxe2Jm0fczeHtMOAfL8ohTekfMGa4HltxiFCMl3/Bwb4d0/wAH/sG+D9L0mxs9L0yz8YWkdvaWkKwQQKLO9wqIoCqB6AV9MaZ8UvEH7LV1HpPxQ1Rta8GzSrb6T49ljSE2zMdqW2sqgWOGQnAS8RVt5SSki28hiFz85/8ABxcpP7FPhk4OB4ztcnHT/Q7yuvG4ehRy6rCjHlstV1+ff1PF4fzLMcdxThMRj6rqc09Hf3fSK0St1Vk11Rl/8EBvAWhfE3/gn14u0XxJouk+IdHvPGt6k9hqdnHd204+xWIw0cgKsOTwR3rH/b4/4IGeHfFmhah4m+BcMfhzxFCGuH8LTXH/ABK9U7mO2Zz/AKJKf4Fz5BIVSIQTKvXf8G5//Jj/AIl/7He9/wDSKxr76rTB4GhisvpQrRv7q16rTozlzviLMMo4mxdfA1HH95K6+zLXaS2f59mmfz0/sh/8FFPin+wNb+KvDOiyTR2N808NxourW5VtF1JG8tpVjkGYZVZCksTLhipBCuA69l+yz8YPjB8S9S1D4hw6T4g8Q6ro+vDW/DXiaWCV7SbX4I7ljpDXLODIl7ZLfaawUyOJLjTo3ZBFbivaP+DhX9kWz+H3xJ8P/F3Q7RbW38ZOdK18RqFQ38Ue6Cb3eWBJFboP9EQ8lmNcB8OP+CuNr4Q/4JxaX8I9Y8P6hrXifwyqJompxXfl/YGsrpLzSJQpTa32aSG2ULuHy26nByRXy8VLC4l4fFVWo003Hs77en6P0P2CrKnm+V080yjBxlUxEkqvRxtdSb2urqzu1zJq6d9P2Z+EfxS0X44fCzw54y8O3JvNB8Vabb6rp8xXazwTRrIm5eqttYZU8g5B5FdFXyR/wR88caXe/BPxl4O0V0Gg+C/FdxP4ciLZkGg6tDBremsRkkKIdRMS55xBjC42j63r7/D1faUoze/X16/ifzXmmDWFxdShG9k9L7uL1i36ppifx/hX8Z+Ny9uwII6/0PU8ehr+zD+P8K/jQrY88+2v+CdH/Bc/4sfsIw6X4Xvpo/HHw1tZVVtE1PLXOnwFvnFnPw0eB0R98fXCjJav6FNd/aO8L+H/ANmy4+LEl4zeCrfw6fFIulX55bL7P9pVlBI+Zo8YU8lmA+v8iOM9s/19vbvX7+fEjXL5f+DX63uFuMTf8K70613+Z0h8+CIrn/rlxQB+ZP8AwUS/4LYfFr9vmK/8PzXEHg34dzTHZ4f0snddRhtyfa5yd8xGMkYRM87M18q/DEbfib4eX/qJ2/8A6NFYf4Y9R6e1bnwy/wCSleHv+wlbf+jVoA/ow/4LT+L7jTNP+GWl2sscU23xXrsDTBjDFcWXhfUhayvg9I7m4gYE45A5GefP/wBq7XPDvh+1+EcXh39qr+1P7D8V28Gn61PfeHjaeCW+wXcUV1MbGzi/cMheBo5v3U3mCFngWRp4+s/4LVSSWHiX4cXH2czQz+GfGtsW3BQjR6XDf4JbCjdHYTLye+cEA4b+3H4/+J2n6d4PvLP4G3mh6zb6tc/Zn8P32nazqM0DafdC8a3h2c3C23mtF+6nHmBSYZceW/z2K/iVb33jsm+i7Nfj8j9OyeNsJgrJXcau7gusl9pN+tum6a0PGfB/iv8A4UtZfFz4b658ftN1aG0ij8W2VrY6lo8ujeKZby7ma+3iSJ7u3fesVy0KXKbWupArSiN5pPvL4nfHT9n34xaJa6d4k+JHw1v7WxvItQtwPF1tbyW9xFnZKjxzq6suTgg96+AdI8daT8Er3wb4w+GPgE3ngnwBb3HiS80W38T2niDTdM0ycNaahcz3khWfT1dt00kExmL3GnlxBCYryRvuQ+M/iUD/AMm06H/4Venf/GqrASSjKL1Wi2lJW1f3atdNtjLiKi5VKdWK5Xdu/PTg+b3U7rT3rJSdm9ZWu0iuLv8AZrZolHxH8L7p/wDVj/hZM37znHH+mc8gjjuK8R179kb9mHVf2vPEHxFufi54QsVvtCTT7Sxs/G8drfaZqmHim1GO5W4EqymARoAScvJcM+8uMec+I/i3qlz+0r8XvBureBtJ8N6X
